all: program1 program2 program3

program1: lcs1.cpp timeProg.h
	g++ lcs1.cpp timeProg.h -o program1

program2: lcs2.cpp timeProg.h
	g++ lcs2.cpp timeProg.h -o program2

program3: lcs3.cpp timeProg.h
	g++ lcs3.cpp timeProg.h -o program3

clean:
	rm program1
	rm program2
	rm program3